---
title: "Evaluación del crecimiento en cautiverio de _Crocodylus moreletii_ en ausencia de refugio"
subtitle: "Elaborado por Jhosse Paul Márquez Ruíz"
author: "Juan Saúl Baez Torreblanca"
date: "`r Sys.Date()`"
output:
        ioslides_presentation:
          css: ./stylesheets/reporte.css
          logo: ../Imagenes/logo.jpg
          smaller: yes
          widescreen: yes
---

```{r paqueterias, include = F, echo = F}
library(dygraphs)
library(ggplot2)
library(stargazer)
```

# Data Loggers
```{r Data_Loggers, echo = FALSE, include = FALSE}
source("../Analisis/Data_Loggers.R")
```

## Temperatura
<div id="graphdiv">
```{r dygraph_temperatura, echo = FALSE}
dygraph(Temp) %>%
        dyRoller(rollPeriod = 1) %>% 
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(labelsSeparateLines = T, labelsDiv = "DLTemp")
```
</div>

<div id="DLTemp", class="legend">
</div>

## Luz
<div id="graphdiv">
```{r dygraph_luz, echo = FALSE}
dygraph(Luz) %>%
        dyRoller(rollPeriod = 7) %>% 
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(labelsSeparateLines = T, labelsDiv = "DLLuz")
```
</div>

<div id="DLLuz", class="legend">
</div>


# Longitud Hocico-Cola

## Crecimiento

```{r Datos_LHC, echo = F, include = FALSE}
source("../Analisis/Analisis_LHC.R")
```

<div id="graphdiv">
```{r LHC CR, echo = F}
dygraph(data = LHC_XTS[, ID$Resguardo == "CR"], width = 400, height = 300,
        main = "Con Resguardo", group = "LHC") %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(labelsSeparateLines = T, labelsDiv = "LHCCR",
                 show = "onmouseover") %>% 
        dyAxis("x", rangePad = 20) %>%
        dyOptions(drawPoints = T, pointSize = 2)
```
</div>
        
<div id="LHCCR", class="legend">
</div>
        
<div id="graphdiv">
```{r LHC SR, echo = F}
dygraph(data = LHC_XTS[, ID$Resguardo == "SR"], width = 400, height = 300,
        main = "Sin Resguardo") %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(width = 500, labelsDiv = "LHCSR", show = "onmouseover",
                 labelsSeparateLines = T) %>% 
        dyAxis("x", rangePad = 20) %>%
        dyOptions(drawPoints = T, pointSize = 2)
```
</div>
        
<div id="LHCSR", class="legend">
</div>
        
## Comparación de los grupos
        

```{r ggplot_LHC, echo = F, fig.align = "center", fig.width = 10}
ggplot(na.omit(Datos), aes(x = factor(MARCA), y = LHC)) +
        facet_grid(. ~ TinaGrande + Tina, scales = "free") +
        geom_boxplot(aes(color = factor(Resguardo))) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        labs(title = "Longitud Hocico-Cloca") +
        labs(x = "Marca", y = "LHC", color = "Resguardo")
```

## Comparación en la LHC

```{r Comparacion_LHC, echo = F, comment = NA, results="asis"}
stargazer(model_LHC, type = "html", style = "all",
          title = "Modelo lineal de efectos mixtos", 
          dep.var.caption = "Variable Dependiente",
          dep.var.labels = "Longitud Hocico-Cola",
          covariate.labels = c("Con Resguardo", "Sin Resguardo"),
          align = T, single.row = T,
          intercept.bottom = F)
```


# Circunferencia de la Cola

## Crecimiento

```{r Datos_Cola, echo = F}
source("../Analisis/Analisis_Cola.R")
```

<div id="graphdiv">
```{r dygraph_ColaCR, echo = F}
dygraph(data = Cola_XTS[, ID$Resguardo == "CR"], width = 400, height = 300,
        main = "Con Resguardo", group = "Cola") %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(labelsSeparateLines = T, labelsDiv = "ColaCR",
                 show = "onmouseover") %>% 
        dyAxis("x", rangePad = 20) %>%
        dyOptions(drawPoints = T, pointSize = 2)
```
</div>
        
<div id="ColaCR", class="legend">
</div>
        
<div id="graphdiv">
```{r dygraph_ColaSR, echo = F}
dygraph(data = Cola_XTS[, ID$Resguardo == "SR"], width = 400, height = 300,
        main = "Sin Resguardo") %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(width = 500, labelsDiv = "ColaSR", show = "onmouseover",
                 labelsSeparateLines = T) %>% 
        dyAxis("x", rangePad = 20) %>%
        dyOptions(drawPoints = T, pointSize = 2)
```
</div>
        
<div id="ColaSR", class="legend">
</div>
        
## Comparación de los grupos
        
```{r ggplot_Cola, echo = F, fig.align = "center", fig.width = 10}
ggplot(na.omit(Datos), aes(x = factor(MARCA), y = COLA)) +
        facet_grid(. ~ TinaGrande + Tina, scales = "free") +
        geom_boxplot(aes(color = factor(Resguardo))) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        labs(title = "Longitud de la cola") +
        labs(x = "Marca", y = "Cola", color = "Resguardo")
```

## Comparación en la circunferencia de la cola

```{r Comparacion_Cola, echo = F, comment = NA, results="asis"}
stargazer(model_COLA, type = "html", style = "all",
          title = "Modelo lineal de efectos mixtos", 
          dep.var.caption = "Variable Dependiente",
          dep.var.labels = "Longitud de la cola",
          covariate.labels = c("Con Resguardo", "Sin Resguardo"),
          align = T, single.row = T,
          intercept.bottom = F)
```


# Peso

## Crecimiento

```{r Datos_Peso, echo = F}
source("../Analisis/Analisis_Peso.R")
```

<div id="graphdiv">
```{r dygraph_PesoCR, echo = F}
dygraph(data = Peso_XTS[, ID$Resguardo == "CR"], width = 400, height = 300,
        main = "Con Resguardo", group = "Peso") %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(labelsSeparateLines = T, labelsDiv = "PesoCR",
                 show = "onmouseover") %>% 
        dyAxis("x", rangePad = 20) %>%
        dyOptions(drawPoints = T, pointSize = 2)
```
</div>

<div id="PesoCR", class="legend">
</div>

<div id="graphdiv">
```{r dygraph_PesoSR, echo = F}
dygraph(data = Peso_XTS[, ID$Resguardo == "SR"], width = 400, height = 300,
        main = "Sin Resguardo") %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
        dyLegend(width = 500, labelsDiv = "PesoSR", show = "onmouseover",
                 labelsSeparateLines = T) %>% 
        dyAxis("x", rangePad = 20) %>%
        dyOptions(drawPoints = T, pointSize = 2)
```
</div>
<div id="PesoSR", class="legend">
</div>

## Comparación de los grupos

```{r Limpieza_Peso, echo = F, include = F}
source("../Analisis/Analisis_Peso.R")
```

```{r ggplot_Peso, echo = F, fig.align = "center", fig.width = 10}
ggplot(na.omit(Datos), aes(x = factor(MARCA), y = PESO)) +
        facet_grid(. ~ TinaGrande + Tina, scales = "free") +
        geom_boxplot(aes(color = factor(Resguardo))) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        labs(title = "Longitud de la Peso") +
        labs(x = "Marca", y = "Peso", color = "Resguardo")
```

## Comparación en la longitud de la Peso

```{r Comparacion_Peso, echo = F, comment = NA, results="asis"}
stargazer(model_Peso, type = "html", style = "all",
          title = "Modelo lineal de efectos mixtos", 
          dep.var.caption = "Variable Dependiente",
          dep.var.labels = "Longitud de la Peso",
          covariate.labels = c("Con Resguardo", "Sin Resguardo"),
          align = T, single.row = T,
          intercept.bottom = F)
```
